# Generated by Django 4.1.3 on 2023-09-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=300, null=True)),
                ("total", models.FloatField()),
            ],
            options={"db_table": "questions",},
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "question_types",},
        ),
        migrations.CreateModel(
            name="SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=100, null=True)),
                ("ques", models.CharField(max_length=1000)),
                ("sub_mark", models.FloatField()),
            ],
            options={"db_table": "sub_questions",},
        ),
        migrations.CreateModel(
            name="SubQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=1000)),
                ("status", models.BooleanField()),
            ],
            options={"db_table": "sub_question_answers",},
        ),
        migrations.CreateModel(
            name="SubQuestionMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.FloatField()),
            ],
            options={"db_table": "sub_question_marks",},
        ),
    ]
