# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_subquestionmark'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='questiontype',
            table='question_types',
        ),
        migrations.AlterModelTable(
            name='subquestion',
            table='sub_questions',
        ),
        migrations.AlterModelTable(
            name='subquestionanswer',
            table='sub_question_answers',
        ),
        migrations.AlterModelTable(
            name='subquestionmark',
            table='sub_question_marks',
        ),
    ]
