# Generated by Django 4.2.5 on 2023-10-25 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroom',
            name='students',
            field=models.ManyToManyField(related_name='joined_rooms', through='rooms.ExamRoomHasStudents', to=settings.AUTH_USER_MODEL),
        ),
    ]
