# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_examroom_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examroom',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='examroomhasstudents',
            table='room_has_students',
        ),
    ]
