# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quizmark_quiz_alter_quizmark_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quiz',
            table='quizzes',
        ),
        migrations.AlterModelTable(
            name='quizmark',
            table='quiz_marks',
        ),
    ]
